spring:
    jpa:
        hibernate:
            ddl-auto: validate
            criteria:
                literal_handling_mode: BIND
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml

    datasource:
        url: jdbc:postgresql://localhost:5432/phonebook
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 10
            idle-timeout: 30000
            connection-timeout: 30000
            max-lifetime: 1800000
            pool-name: PhonebookHikariCP
            connection-test-query: SELECT 1
            initialization-fail-timeout: 1
            auto-commit: true
            transaction-isolation: TRANSACTION_READ_COMMITTED
            leak-detection-threshold: 20000
            register-mbeans: true
            catalog: public
            connection-init-sql: SELECT 1

springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    packages-to-scan: com.ezy.phonebookapp.entrypoint
    swagger-ui:
        enabled: true
        path: /swagger-ui.html

jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
    deserialization:
        fail-on-null-for-primitives: true
