spring:
  flyway:
    baselineOnMigrate: true
    enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace